services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: auth-service
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - auth-db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  auth-db-data: